firstproject/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', include('personal_site.urls', namespace="personal_site")),
    url(r'^projects/', include('projects.urls', namespace="projects")),
    # url(r'^blog/', include('blog.urls')),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^admin/', include(admin.site.urls)),
    #hey
)

personal_site/urls.py
from django.conf.urls import patterns, url

from personal_site import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),

)

polls/urls.py
from django.conf.urls import patterns, url

from polls import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<poll_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
    url(r'^(?P<poll_id>\d+)/results/$', views.results, name='results'),
    # ex: /polls/5/vote/
    url(r'^(?P<poll_id>\d+)/vote/$', views.vote, name='vote'),
)

projects/urls.py
from django.conf.urls import patterns, url

from projects import views

urlpatterns = patterns('',
    url(r'^$', views.index, name='index'),
    url(r'^(?P<project_id>\d+)/$', views.detail, name='detail'),
    # ex: /polls/5/results/
)

personal_site/models.py
from django.db import models
import re
# Create your models here.





class Basic(models.Model):
	title = models.CharField(max_length=100)
	pub_date = models.DateTimeField('date published')
	order = models.IntegerField()

	def __unicode__(self):  # Python 3: def __str__(self):
		return self.title

	def id2(self):
		return re.sub(r'\s+', '', self.title)

	class Meta:
		abstract = True

class Title(Basic):
	sub_title = models.CharField(max_length=100)

class BasicTextSection(Basic):

	main_body = models.TextField(max_length=5000)


	def __unicode__(self):  # Python 3: def __str__(self):
		return self.title





class Choice(models.Model):
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):  # Python 3: def __str__(self):
       return self.choice_text

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.
class Poll(models.Model):
    question = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
  
    def was_published_recently(self):
    	return self.pub_date >= timezone.now() - datetime.timedelta(days=1)

    def __unicode__(self):  # Python 3: def __str__(self):
    	return self.question
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'
    
class Choice(models.Model):
    poll = models.ForeignKey(Poll)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __unicode__(self):  # Python 3: def __str__(self):
       return self.choice_text

projects/models.py
from django.db import models
import re

# Create your models here.
class Project(models.Model):
	title = models.CharField(max_length=100)
	pub_date = models.DateTimeField('date published')
	url = models.URLField()
	def __unicode__(self):  # Python 3: def __str__(self):
		return(self.title)


class ProjectSection(models.Model):
	proj = models.ForeignKey(Project)
	section_title = models.CharField(max_length=100)
	main_body = models.TextField(max_length=5000)
	order = models.IntegerField()


	def id2(self):
		return re.sub(r'\s+', '', self.section_title)

	def __unicode__(self):  # Python 3: def __str__(self):
		return(self.main_body)

personal_site/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from personal_site.models import BasicTextSection, Title
from django.template import RequestContext, loader

def index(request):
	title = Title.objects.order_by('order')[:1]
	sections = BasicTextSection.objects.order_by('order')
	template = loader.get_template('personal_site/index.html')
	context = {'sections': sections, 'title': title}
	return render(request, 'personal_site/index.html', context)
	"""
    latest_poll_list = Poll.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {'latest_poll_list': latest_poll_list}
    """

polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from polls.models import Choice, Poll
from django.template import RequestContext, loader

def index(request):
    latest_poll_list = Poll.objects.order_by('-pub_date')[:5]
    template = loader.get_template('polls/index.html')
    context = {'latest_poll_list': latest_poll_list}
    return render(request, 'polls/index.html', context)

def detail(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/detail.html', {'poll': poll})

def results(request, poll_id):
    poll = get_object_or_404(Poll, pk=poll_id)
    return render(request, 'polls/results.html', {'poll': poll})

def vote(request, poll_id):
    p = get_object_or_404(Poll, pk=poll_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the poll voting form.
        return render(request, 'polls/detail.html', {
            'poll': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))


# Create your views here.

projects/views.py
from django.shortcuts import render, get_object_or_404, get_list_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from projects.models import ProjectSection, Project
from django.template import RequestContext, loader
# Create your views here.



def index(request):
    latest_project_list = Project.objects.order_by('-pub_date')[:5]
    template = loader.get_template('projects/index.html')
    context = {'latest_project_list': latest_project_list}
    return render(request, 'projects/index.html', context)

def detail(request, project_id):
	project = get_object_or_404(Project, pk=project_id)
	context = {'project': project}
	return render(request, 'projects/detail.html', context)

personal_site/templates/personal_site/index.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
	<meta name="description" content="   ">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Framework Demo</title>
  <script src="{% static "personal_site/jquery-2.1.0.js" %}"></script>
  <link rel="stylesheet" href="{% static "personal_site/frames.css" %}" />
  <link rel="stylesheet" href="{% static "personal_site/demo.css" %}" />
  <!--[if lt IE 9]>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7/html5shiv.js"></script>
  <script src="http://cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>
  <![endif]-->
</head>
<body id="top">
<div class="nav-fixed-left">

<ul>
  <h5>
    <li> <a href="/">Home</a> </li>
    <li> <a href="/projects/">Projects</a> </li>
    <li> <a href="/polls/">Django Tutorial</a> </li>
  </h5>
</ul>

</div>

  <div class="container">
     <div class="nav-fixed">
<ul>
	<button id="home"><li>Home</li></button>

  {% if sections %}
 
    {% for sec in sections %}
        <button id="{{ sec.id2 }}Button"><li>{{ sec.title }}</li></button>
    {% endfor %}

{% else %}
    <p>No sections are available.</p>
{% endif %}

</ul>


</div>




<div class="container">
    <script>


    $("#home").click(function() {
      $('html, body').animate({
    scrollTop: $("#top").offset().top
      }, 1000);
    }); 

      {% if sections %}
     
        {% for sec in sections %}
      $( "#{{ sec.id2 }}Button").click(function() {
      $('html, body').animate({
    scrollTop: $("#{{ sec.id2 }}").offset().top - 25
      }, 1000);
    }); 
        {% endfor %}

    {% else %}
        <p>No sections are available.</p>
    {% endif %}




    </script>




      {% if title %}
     
        {% for sec in title %}
          <div id="{{ sec.id2 }}" class="container">
 

            <h1><div id="myName" class="title">{{sec.title}}</div><span class="subtitle">{{ sec.sub_title }}</span></h1> 
          </div>
        {% endfor %}

    {% else %}
        <p>No title is available.</p>
    {% endif %}


  


      {% if sections %}
     
        {% for sec in sections %}
          <div id="{{ sec.id2 }}" class="container">
            <h1>{{ sec.title }}</h1>
            <div class="grid_5-box">{{ sec.main_body }}</div>
          </div>
        {% endfor %}

    {% else %}
        <p>No sections are available.</p>
    {% endif %}



</div>
</div>
</body>
</html>

polls/templates/polls/detail.html
<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

polls/templates/polls/index.html
{% if latest_poll_list %}
    <ul>
    {% for poll in latest_poll_list %}
        <li><a href="{% url 'polls:detail' poll.id %}">{{ poll.question }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

polls/templates/polls/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' poll.id %}">Vote again?</a>

projects/templates/projects/detail.html
<!doctype html>
{% load staticfiles %}
<html>
<head>
  <meta charset="utf-8">
  <meta name="description" content="   ">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <script src="{% static "personal_site/jquery-2.1.0.js" %}"></script>
  <link rel="stylesheet" href="{% static "personal_site/frames.css" %}" />
  <link rel="stylesheet" href="{% static "personal_site/demo.css" %}" />

</head>
<body id='top'>

<div class="nav-fixed-left">

<ul>
  <h5>
    <li> <a href="/">Home</a> </li>
    <li> <a href="/projects/">Projects</a> </li>
    <li> <a href="/polls/">Django Tutorial</a> </li>
  </h5>
</ul>

</div>


<div class="container">


<div class='nav-fixed'>
<ul>
  <button id="home"><li>{{project.title}}</li></button>


  {% if project %}


    {% for sec in project.projectsection_set.all %}
        <button id="{{ sec.id2 }}Button"><li>{{ sec.section_title }}</li></button>
    {% endfor %}

{% else %}
    <p>No project is available.</p>
{% endif %}

</ul>
</div>



</div>
<div class='container'>
<div class='container'>
  {% if project %}

  <div class='container'>
    
    <h1><div class='title'>{{project.title}}</div></h1>

    <p class='subtitle'>Source: <a href="{{project.url}}" target="blank">{{project.url}}</a></p>
    
    </div>
{% else %}
    <p>No project is available.</p>
{% endif %}


  <script>


    $("#home").click(function() {
      $('html, body').animate({
    scrollTop: $("#top").offset().top
      }, 1000);
    }); 

      {% if project %}
     
        {% for sec in project.projectsection_set.all %}
      $( "#{{ sec.id2 }}Button").click(function() {
      $('html, body').animate({
    scrollTop: $("#{{ sec.id2 }}").offset().top - 25
      }, 1000);
    }); 
        {% endfor %}

    {% else %}
        <p>No project is available.</p>
    {% endif %}




    </script>


  {% if project %}


    {% for sec in project.projectsection_set.all %}
          <div id="{{ sec.id2 }}" class="container">
            <h1>{{ sec.section_title }}</h1>
            <div class="grid_5-box">{{ sec.main_body }}</div>
          </div>
    {% endfor %}

{% else %}
    <p>No project is available.</p>
{% endif %}

</div>
</div>
</body>
</html>

projects/templates/projects/index.html
{% if latest_project_list %}
<ul>
    {% for project in latest_project_list %}
    <li><a href="{% url 'projects:detail' project.id %}">{{ project.title }}</a>
    </li>
    {% endfor %}
</ul>
{% else %}
<p>No projects are available.</p>
{% endif %}